openapi: 3.0.1
info:
  title: Swagger Petstore
  description: |
    This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key "special-key" to test the authorization     filters.

    **All api maybe return 401 code if it need auth.**
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore.swagger.io/v2
  - url: http://petstore.swagger.io/v2

tags:
  - name: Regular
    description: Test all features
  - name: Edge
    description: Test things that are prone to bugs

paths:
  /pet/findByStatus:
    get:
      x-$path: github.com/gopenapi/gopenapi/internal/delivery/http/handler.PetHandler.FindPetByStatus
      tags:
        - Regular
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  /pet/{id}:
    get:
      x-$path: github.com/gopenapi/gopenapi/internal/delivery/http/handler.PetHandler.GetPet
      tags:
        - Regular
      operationId: getPetById
      security:
        - api_key: [ ]

    delete:
      x-$path: ./internal/delivery/http/handler.PetHandler.DelPet
      tags:
        - Regular
      security:
        - api_key: [ ]
  /pet:
    put:
      x-$path: ./internal/delivery/http/handler.PetHandler.PutPet
      # They will be merged if they have same key.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
      tags:
        - Regular
      security:
        - api_key: [ ]

  /test_recursion:
    post:
      x-$path: ./internal/delivery/http/handler.OtherHandler.TestRecursion
      tags:
        - Edge
      security:
        - api_key: [ ]

components:
  schemas:
    Category:
      x-$schema: github.com/gopenapi/gopenapi/internal/model.Category
    Tag:
      x-$schema: ./internal/model.Tag
    Pet:
      x-$schema: github.com/gopenapi/gopenapi/internal/model.Pet
    TestRecursion:
      x-$schema: github.com/gopenapi/gopenapi/internal/model.TestRecursion

  responses:
    200:
      description: Success
      content:
        application/json:
          schema:
            type: string
            example: ok

    400:
      description: Invalid Params
      content:
        application/json:
          schema:
            type: object
            properties:
              msg:
                type: string
                example: 参数不正确

    401:
      description: 没权限
      content:
        application/json:
          schema:
            type: object
            properties:
              msg:
                type: string
                example: 没权限


  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header